name: JoinPlugin
version: 2.4
main: me.hyperburger.joinplugin.JoinPlugin
api-version: 1.13
authors: [ HyperBurger, GalaxyVN ]
description: A Custom Coded Join Plugin
softdepend:
  - PlaceholderAPI
  - SuperVanish
  - PremiumVanish
commands:
  JoinPlugin:
    description: JoinPlugin Main Command
    aliases:
      - jp
      - joinp